// Modal and interaction helpers for the dashboard.
(function(){
  let metricStore=[];
  let pricedStore=[];
  const ABOUT={
    "ACWI":"ACWI measures how far the broad global equity market is above or below its 200-day moving average. It is a simple trend measure for the overall world stock market.",
    "US equities":"This shows the S&P 500 relative to its 200-day moving average. It helps identify whether the US equity market is in an established uptrend or downtrend.",
    "Europe":"This shows European equities relative to their 200-day moving average. It provides a quick view of the trend in developed European markets.",
    "Emerging markets":"This shows emerging-market equities relative to their 200-day moving average. It helps identify whether the broad EM market is trending positively or negatively.",
    "US volatility (VIX)":"VIX reflects option-implied expected volatility for the US stock market over roughly the next 30 days. Higher values generally mean more near-term uncertainty is being priced.",
    "Europe volatility (VSTOXX)":"VSTOXX reflects option-implied expected volatility for European equities over roughly the next 30 days. Higher readings indicate more uncertainty being priced.",
    "Emerging-market volatility (VXEEM)":"VXEEM reflects option-implied expected volatility for emerging-market equities. It is a useful gauge of stress specifically in riskier equity markets.",
    "ACWI drawdown":"This measures how far ACWI is below its most recent high. A value near zero means the global equity market is close to its peak; a more negative value indicates a larger decline.",
    "US CAPE":"CAPE compares the S&P 500 price with ten years of inflation-adjusted earnings. Higher readings mean investors are paying a higher long-term price for earnings.",
    "US 10Y yield":"The US 10-year Treasury yield is a key global interest-rate benchmark. It influences borrowing costs, bond valuations and the discount rate used for many assets.",
    "Gold":"Gold is shown as a cross-asset price reference. It can provide context on inflation concerns, real-rate movements and demand for defensive assets."
  };
  function esc(v){return String(v??"—").replace(/[&<>\"']/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[s]))}
  function storeMetrics(items){return (items||[]).map(item=>{const id=String(metricStore.push(item));return{id,item}})}
  function metricCard(item,id,band){return `<article class="metric-card" tabindex="0" role="button" data-open-metric="${id}" aria-label="Open details for ${esc(item.name)}"><div class="metric-top"><div class="metric-name">${esc(item.name)}</div></div><div class="metric-value">${esc(item.display)}</div><div class="metric-meta">${esc(item.detail)}</div>${band}</article>`}
  function renderMetrics(target,items,bandFn){const el=document.getElementById(target);if(!el)return;const entries=storeMetrics(items);el.innerHTML=entries.map(x=>metricCard(x.item,x.id,bandFn(x.item))).join("")||'<div class="empty">No data.</div>'}
  function renderPriced(items){const el=document.getElementById("pricedInGrid");if(!el)return;pricedStore=(items||[]);el.innerHTML=pricedStore.map((i,n)=>`<article class="priced-card" tabindex="0" role="button" data-open-priced="${n}" aria-label="Open details for ${esc(i.name)}"><h4>${esc(i.name)}</h4><div class="big">${esc(i.display)}</div><p>${esc(i.explanation)}</p></article>`).join("")||'<div class="empty">No market-pricing data.</div>'}
  function openModal(item,type){const modal=document.getElementById("metricModal"),title=document.getElementById("metricModalTitle"),body=document.getElementById("metricModalBody");if(!modal||!title||!body)return;title.textContent=item.name||"Indicator";if(type==='priced'){body.innerHTML=`<div class="modal-content-top"><div><div class="modal-big-value">${esc(item.display)}</div><p class="modal-detail">${esc(item.explanation||"")}</p></div><aside class="modal-info"><div class="eyebrow">ABOUT</div><p>${esc(item.explanation||"Market-derived signal used to provide context for current market pricing.")}</p></aside></div>`}else{body.innerHTML=`<div class="modal-content-top"><div><div class="modal-big-value">${esc(item.display)}</div><p class="modal-detail">${esc(item.detail||"")}</p></div><aside class="modal-info"><div class="eyebrow">ABOUT THIS INDICATOR</div><p>${esc(ABOUT[item.name]||item.detail||"This indicator provides context for current market conditions.")}</p></aside></div>${item.band?`<div class="modal-tracker">${window.dashboardBandHtml(item,false)}</div>`:""}`}modal.hidden=false;modal.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");const close=modal.querySelector(".metric-modal-close");if(close)close.focus()}
  function closeModal(){const m=document.getElementById("metricModal");if(!m)return;m.hidden=true;m.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open")}
  window.dashboardMetricUI={
    init(data,bandFn){window.dashboardBandHtml=bandFn;metricStore=[];renderMetrics("equityGrid",data.equities,bandFn);renderMetrics("riskGrid",data.risk,bandFn);renderMetrics("valuationGrid",data.valuation,bandFn);renderMetrics("crossAssetGrid",data.cross_asset,bandFn);renderPriced(data.priced_in);},
    bind(){if(window.__metricUIBound)return;window.__metricUIBound=true;document.addEventListener("click",e=>{const m=e.target.closest("[data-open-metric]");if(m){const item=metricStore[Number(m.dataset.openMetric)-1];if(item)openModal(item,"indicator");return}const p=e.target.closest("[data-open-priced]");if(p){const item=pricedStore[Number(p.dataset.openPriced)];if(item)openModal(item,"priced");return}if(e.target.closest("[data-close-modal]"))closeModal()});document.addEventListener("keydown",e=>{if(e.key==='Escape'){closeModal();return}const el=document.activeElement;if((e.key==='Enter'||e.key===' ')&&el?.matches?.('[data-open-metric],[data-open-priced]')){e.preventDefault();el.click()}})}
  };
})();
